apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: mycontainer
        image: gcr.io/amplified-asset-328305/my-web-server:latest
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
